x = int(input('Enter first number: '))
y = int(input('Enter second number: '))
print('X + Y = ', x + y)
print('X - Y = ', x - y)
print('X / Y = ', x / y)
print('X * Y = ', x * y)
print('X concatenation Y = ', str(x) + str(y))